[project]
name = "youtube-wallpaper-prank"
version = "1.0.0"
description = "Sets wallpaper to YouTube video thumbnail"
dependencies = [
    "requests>=2.25.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"