[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fake-progress-bars"
version = "1.0.0"
description = "Shows convincing fake system maintenance progress dialogs"
dependencies = []

[project.scripts]
fake-progress-bars = "fake_progress_bars:main"