[project]
name = "screen-rotation-prank"
version = "1.0.0"
description = "Rotates screen orientation for prank"
dependencies = [
    "rotate-screen>=1.0.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"