[project]
name = "color_filter_chaos"
version = "1.0.0"
description = "Applies random color filters to the screen"
dependencies = [
    "pywin32>=306"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"