[project]
name = "move-mouse"
version = "1.0.0"
description = "Moves mouse cursor randomly"
dependencies = [
    "pyautogui>=0.9.50"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"