[project]
name = "play_sound"
version = "1.0.0"
description = "Plays Windows system sounds"
dependencies = [
    "pywin32>=306"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"